version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    build: ./weather-wear
    ports:
      - "3000:3000"
    depends_on:
      - backend

